name: Build app
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repo
        uses: actions/checkout@v5

      - name: Build step
        run: ci/build-app.sh

      - name: Unit tests
        run: ci/unit-test-app.sh

      - name: Build docker
        run: ci/build-docker.sh

      - name: push docker
        run: ci/push-docker.sh

        
