name: Build app
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build step
        run: ci/build-app.sh

      - name: Unit tests
        run: ci/unit-test-app.sh

      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-file: true

  linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

        
